name: levy_core
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  levy_dependencies:
    path: ../levy_dependencies
#    git:
#      url: https://github.com/andreleitejr/levy_dependencies.git

  auto_route:
  auto_route_generator:
  flutter_svg:
  google_maps_flutter:
  injectable:
  json_annotation:
  shimmer:
  slang:
  uuid:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable:
  injectable_generator: